### ISSUE TITLE
allow specifying path to phpstan neon config

### ISSUE THREAD

**Issue by JackNoordhuis** [matlad/phpstancs#10]
my project is set up to have the basic rules and path analysis information in the `phpstan.neon` file and then each tool gets its own `tool-name.phpstan.neon` that includes the base config

**Comment by matlad** [comment]
Hi, this is quite problem, this tool gets only parameters passed by PHPStom, so no space to pass config file location(name). So I would be forced to search yours, not standard, config file name together with standard phpstan.neon and give yours bigger priority. I don't won't this in main but i'm in good mood, so I put it in JackNoordhuis branche, where you can use it. (composer require --dev matla/phpstancs:dev-JackNoordhuis) phpstancs.phpstan.neon

Is this solution Ok?

**Comment by matlad** [comment]
Hi, phpstorm now support phpstan by him self, so I abandoning this package. And cloaseing all isues
