### ISSUE TITLE
ms windows support

### ISSUE THREAD

**Issue by bingalls** [matlad/phpstancs#3]
In the bin directory, add **phpcs.bat** with the following
```
@echo off
phpcs %1 %2 %3 %4 %5 %6 %7 %8 %9
```

**Comment by matlad** [comment]
I do not have windows with php and I'm lazy to get one, so i'm unable to test this. Is this working? Could you do pull request with this modification?

**Comment by bingalls** [comment]
This works on a local system.
I added a usage hint in a comment in https://github.com/matlad/phpstancs/pull/4
Batch files have a limit of 9 command line args passed in.
Sadly, Windows users are more likely to use a virtual machine, requiring a hack using `vagrant ssh`

**Comment by bingalls** [comment]
Your code looks promising, but it is not working for me. Sadly, batch/cmd lacks `pwd`, afaik. An easy hack is to require `composer global` installs for windows users, which ensures a subdirectory of `%APPDATA%`

**Comment by matlad** [comment]
1. `pwd` can be replaced by `cd`.
2.  How exactly it doesn't work?  Could you give me more info?
Try put something like this in your phpcs.cmd file
``` cmd
@echo %* >> E:\phpstancstest\log.txt
cd >> E:\phpstancstest\log.txt
"%PHPBIN%" "%~dp0\phpcs" %* >> E:\phpstancstest\log.txt
```

**Comment by bingalls** [comment]
```bat
composer global require --dev matla/phpstancs @dev
rem setting PHPBIN makes no difference...
set PHPBIN=C:\tools\php73
rem cd into my project folder with phpstan.neon, which successfully runs phpstan
cd %HOMEPATH%\Code
\tools\php73\php.exe "%APPDATA%\Composer\vendor\matla\phpstancs\bin\phpcs" %*
```

> Project config file at path %APPDATA%\Composer\vendor\matla\phpstancs\bin/../../../../vendor/../phpstan.neon does not exist.
@matlad I replaced output with `%APPDATA%` for general relevance.

**Comment by matlad** [comment]
Ok try
`composer global require --dev matla/phpstancs dev-win_global_support`
do not set `PHPBIN` but `PHP_PEAR_PHP_BIN`  eg.  `set PHP_PEAR_PHP_BIN=C:\tools\php73\php.exe`

**Comment by matlad** [comment]
and be aware, that you must run phpstorm in your project directory

**Comment by matlad** [comment]
@bingalls any news?

**Comment by bingalls** [comment]
Hmm This works much better, but I cannot seem to get past `At least one path must be specified to analyse.` I also tried `--paths-file`

**Comment by matlad** [comment]
Hi, phpstorm now support phpstan by him self, so I abandoning this package. And cloaseing all isues
